FROM registry.redhat.io/rhel10/rhel-bootc:10.0-1758173064

COPY static/ /

RUN dnf -y install firewalld policycoreutils-python-utils audit && \
  rpm-ostree cleanup --repomd && \
  dnf clean all && \
  rm --recursive --force /var/* /tmp/* && \
  chmod +x /etc/rc.d/rc.local && \
  bootc container lint
