FROM ghcr.io/mikefarah/yq:4.50.1 AS yq-binary

FROM quay.io/almalinuxorg/almalinux-bootc:10.1-20260120

COPY static/                /
COPY el10/almalinux/static/ /

COPY --from=yq-binary /usr/bin/yq /usr/bin/yq

RUN dnf -y install firewalld policycoreutils-python-utils audit && \
  rpm-ostree cleanup --repomd && \
  dnf clean all && \
  rm --recursive --force /var/* /tmp/* && \
  chmod +x /etc/rc.d/rc.local && \
  bootc container lint
