FROM ghcr.io/mikefarah/yq:4.47.1 AS yq-binary

FROM quay.io/almalinuxorg/almalinux-bootc:9.6-20250809

COPY static/           /
COPY almalinux/static/ /

COPY --from=yq-binary /usr/bin/yq /usr/bin/yq

RUN dnf config-manager --enable plus && \
  dnf -y install firewalld policycoreutils-python-utils audit && \
  rpm-ostree cleanup --repomd && \
  dnf clean all && \
  rm --recursive --force /var/* /tmp/* && \
  chmod +x /etc/rc.d/rc.local && \
  bootc container lint
