FROM registry.redhat.io/rhel9/rhel-bootc:9.5-1739946498

COPY static/ /

RUN dnf -y install cloud-init && \
    ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN update-crypto-policies --no-reload --set FIPS

