FROM registry.redhat.io/rhel9/rhel-bootc:9.6-1750210962

COPY static/ /

RUN dnf -y install open-vm-tools perl && \
    systemctl enable vmtoolsd.service && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN update-crypto-policies --no-reload --set FIPS
