FROM quay.io/fedora/fedora-bootc:42

# notes:
#   https://docs.fedoraproject.org/en-US/bootc/building-containers/

COPY static/ /

RUN dnf -y install firewalld policycoreutils-python-utils audit openssh yq && \
  rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN bootc container lint --skip var-tmpfiles
