FROM registry.redhat.io/rhel9/rhel-bootc:9.6-1760335990

COPY static/ /

RUN dnf -y install firewalld policycoreutils-python-utils audit && \
  rpm-ostree cleanup --repomd && \
  dnf clean all && \
  rm --recursive --force /var/* /tmp/* && \
  chmod +x /etc/rc.d/rc.local && \
  bootc container lint
