FROM ghcr.io/mikefarah/yq:4.47.1 AS yq-binary

FROM quay.io/almalinuxorg/almalinux-bootc:9.6-20250904

COPY static/           /
COPY almalinux-el9/static/ /

COPY --from=yq-binary /usr/bin/yq /usr/bin/yq

RUN dnf -y install firewalld policycoreutils-python-utils audit && \
  rpm-ostree cleanup --repomd && \
  dnf clean all && \
  rm --recursive --force /var/* /tmp/* && \
  chmod +x /etc/rc.d/rc.local && \
  bootc container lint
