---
name: Container, RHEL
on:
  workflow_dispatch:
  push:
    paths:
      - 'rhel/**'
    branches:
      - main

jobs:
  subs:
    name: Build RHEL bootc image with repo access
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}/rhel
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    container:
      image: registry.access.redhat.com/ubi9/ubi:9.6-1747219013
      options: --privileged

    steps:
      - name: Clone the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Determine tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "TAG=$(cat rhel/Containerfile | head -1 | sed -E "s/.+:(.+)/\1/g")-$(echo ${sha:0:8})-$job" >> $GITHUB_OUTPUT

      - name: Get container tools in UBI builder
        run: dnf -y install podman buildah skopeo

      - name: Access a subscription via activation key
        env:
          SMDEV_CONTAINER_OFF: 1
          orgid: ${{ secrets.RHT_ORGID }}
          activation_key: ${{ secrets.RHT_ACT_KEY }}
        run: subscription-manager register --org=$orgid --activationkey=$activation_key

      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json

      - name: Log in to the RHT terms based registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHT_REG_SVCUSER }}
          password: ${{ secrets.RHT_REG_SVCPASS }}
          auth_file_path: /run/containers/0/auth.json

      - name: Use buildah bud to create the image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ steps.tag.outputs.TAG }}
          containerfiles: |
            ./rhel/Containerfile
          context: ./rhel

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json

      - name: Re-tag the built image
        run: |-
          podman tag ${{ steps.build-image.outputs.image }}:latest ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:latest
          podman tag ${{ steps.build-image.outputs.image }}:${{ steps.tag.outputs.TAG }} ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:${{ steps.tag.outputs.TAG }}

      - name: Push the built image
        env:
          REGISTRY_AUTH_FILE: /run/containers/0/auth.json
        run: |-
          podman push --tls-verify ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:latest
          podman push --tls-verify ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:${{ steps.tag.outputs.TAG }}

      - name: Clean up the subscription
        if: always()
        env:
          SMDEV_CONTAINER_OFF: 1
        run: subscription-manager unregister
