---
name: ISO, Fedora

on:
  workflow_dispatch:

env:
  URL: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Server/x86_64/iso/Fedora-Server-dvd-x86_64-42-1.1.iso

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora:42
      options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Determine tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "TAG=$(cat fedora/Containerfile | head -1 | sed -E "s/.+:(.+)/\1/g")-$job-$(echo ${sha:0:8})" >> $GITHUB_OUTPUT
          mkdir -p bootiso

      - name: Get container tools in builder
        run: dnf install -y lorax

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache
        with:
          path: /tmp/iso
          key: ${{ runner.os }}-fedora-server-dvd

      - name: Pull iso
        if: steps.cache.outputs.cache-hit != 'true'
        run: |-
          mkdir -p /tmp/iso
          curl -L -o /tmp/iso/fedora-server-dvd-42.iso ${{ env.URL }}

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: /tmp/iso
          key: ${{ runner.os }}-fedora-server-dvd
          restore-keys: |
            ${{ runner.OS }}-fedora-cache-

      - name: Generate iso
        run: |-
          mkksiso --skip-mkefiboot --ks kickstart/fedora.ks /tmp/fedora-server-dvd-42.iso fedora-${{ steps.tag.outputs.TAG }}.iso

      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: fedora-${{ steps.tag.outputs.TAG }}
          path: fedora-${{ steps.tag.outputs.TAG }}.iso
          retention-days: 1
