---
name: Container, Almalinux, EL9
on:
  workflow_dispatch:
  push:
    paths:
      - el09/almalinux/**
      - static/**
      - .github/workflows/build_bootc_el09_alma.yml
    branches:
      - main
    tags:
      - 'almalinux/9\.[0-9]+-[0-9]+'
  schedule:
    - cron: '15 0 * * 0'

env:
  DISTRO: "almalinux"
  MAJOR: "9"
  IMAGE_NAME: ${{ github.event.repository.name }}/bootc/alma
  IMAGE_RPM_NAME: ${{ github.event.repository.name }}/rpm/alma
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  info:
    name: Determine build info
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Determine Build Tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "TAG=$(cat el09/${{ env.DISTRO }}/Containerfile | grep -i "${{ env.DISTRO }}" | grep -iE "^from.+bootc" | sed -E "s/.+:(.+)/\1/g")-$(echo $job-${sha:0:8})" >> $GITHUB_OUTPUT

      - name: Get Git Tag Info
        id: git-tag
        run: |-
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "tag=$(echo ${{ github.ref }} | sed 's!refs/tags/${{ env.DISTRO }}/!!g')"
            echo "tag=$(echo ${{ github.ref }} | sed 's!refs/tags/${{ env.DISTRO }}/!!g')" >> $GITHUB_OUTPUT
          else
            echo "TAG=''"
            echo "TAG=''" >> $GITHUB_OUTPUT
          fi

      - name: Output version
        id: determine
        run: |-
          if [[ "${{ steps.git-tag.outputs.TAG }}" != "''" ]]; then
            echo "version=${{ steps.git-tag.outputs.TAG }}"
            echo "version=${{ steps.git-tag.outputs.TAG }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.tag.outputs.TAG }}"
            echo "version=${{ steps.tag.outputs.TAG }}" >> $GITHUB_OUTPUT
          fi
    outputs:
      tag: ${{ steps.determine.outputs.version }}

  build-bootc:
    name: Build bootc image
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-latest' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    needs:
      - info
    permissions:
      packages: write
    container:
      image: quay.io/almalinuxorg/9-base:9.6-20250909
      options: --privileged
    steps:
      - name: Clone the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get container tools into builder
        run: dnf -y install podman buildah skopeo

      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json

      - name: Use buildah bud to create the image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ needs.info.outputs.tag }}
          containerfiles: |-
            el09/${{ env.DISTRO }}/Containerfile
          context: ./.

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json

      - name: Re-tag the built image
        run: |-
          podman tag ${{ steps.build-image.outputs.image }}:${{ needs.info.outputs.tag }} ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}${{ env.MAJOR }}:${{ needs.info.outputs.tag }}-${{ matrix.platform }}

      - name: Push the built image
        env:
          REGISTRY_AUTH_FILE: /run/containers/0/auth.json
        run: |-
          podman push --tls-verify=true ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}${{ env.MAJOR }}:${{ needs.info.outputs.tag }}-${{ matrix.platform }}
    outputs:
      image: ${{ steps.build-image.outputs.image }}
      tag: ${{ needs.info.outputs.tag }}

  build-rpm:
    name: Build rpm oci artifact
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-latest' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    needs:
      - info
    permissions:
      packages: write
    container:
      image: quay.io/almalinuxorg/9-base:9.6-20250909
      # needed for login to ghcr
      options: --privileged
    steps:
      - name: Get container tools into builder
        run: dnf -y install podman createrepo

      - name: Install oras tool
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6 # v1.2.4

      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json

      - name: Create workspace
        run: |-
          mkdir -p /root/rpm

      - name: Download packages
        run: |-
          dnf group install \
            core standard smart-card \
            --releasever ${{ env.MAJOR }} \
            --assumeyes \
            --downloadonly \
            --destdir /root/rpm \
            --installroot /root/rpm \
            --nodocs \
            --refresh
          rm -rf /root/rpm/var
          createrepo /root/rpm

      - name: Upload to ghcr
        working-directory: /root/rpm
        run: |-
          find /root/rpm -type f | sed 's#/root/rpm/##g' | \
            awk 'BEGIN {printf "oras push --artifact-platform \"linux/${{ matrix.platform }}\" --registry-config /run/containers/0/auth.json --no-tty ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/rpm/alma9:${{ needs.info.outputs.tag }}-${{ matrix.platform }}"} {printf " %s:application/vnd.adrp.rpm.v1 ", $0} END{print ""}' | \
            xargs -I {} sh -c "eval {}"
    outputs:
      tag: ${{ needs.info.outputs.tag }}

  merge:
    name: Merge artifacts arch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        artifact:
          - "bootc"
          - "rpm"
    needs:
      - build-bootc
      - build-rpm
    steps:
      - name: Install oras tool
        uses: oras-project/setup-oras@22ce207df3b08e061f537244349aac6ae1d214f6 # v1.2.4

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and pushes
        run: |-
          oras manifest index create \
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ matrix.artifact }}/alma${{ env.MAJOR }}:latest \
            ${{ needs.build-bootc.outputs.tag }}-amd64 ${{ needs.build-bootc.outputs.tag }}-arm64
          oras manifest index create \
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ matrix.artifact }}/alma${{ env.MAJOR }}:${{ needs.build-bootc.outputs.tag }} \
            ${{ needs.build-bootc.outputs.tag }}-amd64 ${{ needs.build-bootc.outputs.tag }}-arm64
    outputs:
      tag: ${{ needs.build-bootc.outputs.tag }}

  zarf:
    name: Build zarf packages
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-latest' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' }}
    needs:
      - merge
    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - arm64
        flavor:
          - rpm
          - bootc
    permissions:
      packages: write
    container:
      image: quay.io/almalinuxorg/9-base:9.6-20250909
    steps:
      - name: Get container tools into builder
        run: |-
          dnf -y install createrepo yum-utils

      - name: Configure docker repo
        run: |-
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

      - name: Install docker
        run: |-
           dnf -y install docker-ce docker-ce-cli containerd.io

      - name: Clone the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install The Latest Release Version of Zarf
        uses: zarf-dev/setup-zarf@10e539efed02f75ec39eb8823e22a5c795f492ae # v1.0.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Zarf package
        run: |-
          zarf package create \
            el09/${{ env.DISTRO }} \
            --confirm \
            --flavor ${{ matrix.flavor }} \
            --set version=${{ needs.merge.outputs.tag }}

      - name: Publish Zarf package
        run: |-
          zarf package publish zarf-*.zst oci://ghcr.io/${{ github.repository_owner }}/zarf
