---
name: Container, Fedora
on:
  workflow_dispatch:
  push:
    paths:
      - fedora/**
      - static/**
      - .github/workflows/build_bootc_fedora.yml
    branches:
      - main
  schedule:
    - cron: '30 0 * * *'

jobs:
  subs:
    name: Build Fedora bootc image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      DISTRO: "fedora"
      IMAGE_NAME: ${{ github.event.repository.name }}/fedora
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    container:
      image: quay.io/fedora/fedora:42
      options: --privileged

    steps:
      - name: Clone the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Determine tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "TAG=$(cat ${{ env.DISTRO }}/Containerfile | grep -i "${{ env.DISTRO }}" | grep -iE "^from.+bootc" | sed -E "s/.+:(.+)/\1/g")-$(echo $job-${sha:0:8})" >> $GITHUB_OUTPUT

      - name: Get container tools into builder
        run: dnf -y install podman buildah skopeo

      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json

      - name: Use buildah bud to create the image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ steps.tag.outputs.TAG }}
          containerfiles: |
            ./${{ env.DISTRO }}/Containerfile
          context: ./.

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json

      - name: Re-tag the built image
        run: |-
          podman tag ${{ steps.build-image.outputs.image }}:latest ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:latest
          podman tag ${{ steps.build-image.outputs.image }}:${{ steps.tag.outputs.TAG }} ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:${{ steps.tag.outputs.TAG }}

      - name: Push the built image
        env:
          REGISTRY_AUTH_FILE: /run/containers/0/auth.json
        run: |-
          podman push --tls-verify=true ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:latest
          podman push --tls-verify=true ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}:${{ steps.tag.outputs.TAG }}
