---
name: Container, RHEL, EL9
on:
  workflow_dispatch:
  push:
    paths:
      - 'el09/rhel/**'
      - .github/workflows/build_bootc_el09_rhel.yml
    branches:
      - main
    tags:
      - 'rhel/9\.[0-9]+-[0-9]+'

env:
  DISTRO: "rhel"
  MAJOR: "9"
  IMAGE_NAME: ${{ github.event.repository.name }}/bootc/rhel
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  info:
    name: Determine build info
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Determine Build Tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "TAG=$(cat el09/${{ env.DISTRO }}/Containerfile | grep -i "${{ env.DISTRO }}" | grep -iE "^from.+bootc" | sed -E "s/.+:(.+)/\1/g")-$(echo $job-${sha:0:8})" >> $GITHUB_OUTPUT
      - name: Get Git Tag Info
        id: git-tag
        run: |-
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            echo "tag=$(echo ${{ github.ref }} | sed 's!refs/tags/${{ env.DISTRO }}/!!g')"
            echo "tag=$(echo ${{ github.ref }} | sed 's!refs/tags/${{ env.DISTRO }}/!!g')" >> $GITHUB_OUTPUT
          else
            echo "TAG=''"
            echo "TAG=''" >> $GITHUB_OUTPUT
          fi
      - name: Output version
        id: determine
        run: |-
          if [[ "${{ steps.git-tag.outputs.TAG }}" != "''" ]]; then
            echo "version=${{ steps.git-tag.outputs.TAG }}"
            echo "version=${{ steps.git-tag.outputs.TAG }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ steps.tag.outputs.TAG }}"
            echo "version=${{ steps.tag.outputs.TAG }}" >> $GITHUB_OUTPUT
          fi
    outputs:
      tag: ${{ steps.determine.outputs.version }}
  build:
    name: Build bootc image
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-latest' || matrix.platform == 'arm64' && 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        platform:
          - amd64
          - arm64
    needs:
      - info
    permissions:
      packages: write
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}/rhel
      REGISTRY: ghcr.io/${{ github.repository_owner }}
    container:
      image: registry.access.redhat.com/ubi9/ubi:9.6-1758184894
      options: --privileged
    steps:
      - name: Clone the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Get container tools in UBI builder
        run: dnf -y install podman buildah skopeo
      - name: Access a subscription via activation key
        env:
          SMDEV_CONTAINER_OFF: 1
          orgid: ${{ secrets.RHT_ORGID }}
          activation_key: ${{ secrets.RHT_ACT_KEY }}
        run: subscription-manager register --org=$orgid --activationkey=$activation_key
      - name: Install insight-client
        run: dnf -y install insights-client
      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json
      - name: Log in to the RHT terms based registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHT_REG_SVCUSER }}
          password: ${{ secrets.RHT_REG_SVCPASS }}
          auth_file_path: /run/containers/0/auth.json
      - name: Use buildah bud to create the image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ needs.info.outputs.tag }}
          containerfiles: |-
            el09/${{ env.DISTRO }}/Containerfile
          context: |-
            el09/${{ env.DISTRO }}
      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json
      - name: Re-tag the built image
        run: |-
          podman tag ${{ steps.build-image.outputs.image }}:${{ needs.info.outputs.tag }} ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}${{ env.MAJOR }}:${{ needs.info.outputs.tag }}-${{ matrix.platform }}

      - name: Push the built image
        env:
          REGISTRY_AUTH_FILE: /run/containers/0/auth.json
        run: |-
          podman push --tls-verify=true ghcr.io/${{ github.repository_owner }}/${{ steps.build-image.outputs.image }}${{ env.MAJOR }}:${{ needs.info.outputs.tag }}-${{ matrix.platform }}

      - name: Clean up the subscription
        if: always()
        env:
          SMDEV_CONTAINER_OFF: 1
        run: |-
          subscription-manager unregister
          insights-client --unregister
    outputs:
      image: ${{ steps.build-image.outputs.image }}

  merge:
    # section pulled from:
    # https://github.com/sredevopsorg/multi-arch-docker-github-workflow/blob/56f5fbaa1757d3e330547bed67e61d084130d69d/.github/workflows/multi-build.yaml#L185
    name: Merge multi-arch
    runs-on: ubuntu-latest
    needs:
      - info
      - build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1.7
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and pushes
        run: |-
          docker buildx imagetools create \
            --tag="ghcr.io/${{ github.repository_owner }}/${{ needs.build.outputs.image }}${{ env.MAJOR }}:${{ needs.info.outputs.tag }}" \
            --tag="ghcr.io/${{ github.repository_owner }}/${{ needs.build.outputs.image }}${{ env.MAJOR }}:latest" \
            ghcr.io/${{ github.repository_owner }}/${{ needs.build.outputs.image }}${{ env.MAJOR }}:${{ needs.info.outputs.tag }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/${{ needs.build.outputs.image }}${{ env.MAJOR }}:${{ needs.info.outputs.tag }}-arm64
