---
name: Build alma iso

on:
  workflow_dispatch:

env:
  URL: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Server/x86_64/iso/Fedora-Server-dvd-x86_64-42-1.1.iso

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/fedora/fedora:43
      options: --privileged

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Determine tag
        id: tag
        env:
          sha: ${{ github.sha }}
          job: ${{ github.run_number }}
        run: |-
          echo "TAG=$(cat fedora/Containerfile | head -1 | sed -E "s/.+:(.+)/\1/g")-$job-$(echo ${sha:0:8})" >> $GITHUB_OUTPUT
          mkdir -p bootiso

      - name: Get container tools in builder
        run: dnf install -y lorax

      - name: Pull iso
        run: |-
          curl -L -O ${{ env.URL }}
          cp ../kickstart/fedora.ks ks.cfg

      - name: Generate iso
        run: |-
          mkksiso --skip-mkefiboot --ks kickstart/fedora.ks /tmp/Fedora-Server-dvd-x86_64-42-1.1.iso fedora-${{ steps.tag.outputs.TAG }}.iso

      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: fedora-${{ steps.tag.outputs.TAG }}
          path: fedora-${{ steps.tag.outputs.TAG }}.iso
          retention-days: 1
